name: Queries-CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - queries/**
  pull_request:
    paths:
      - queries/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: luacheck .

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
